<?php

namespace Tests\Feature\Api;

use App\Models\Branch;
use App\Models\Employee;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class EmployeeTest extends TestCase
{
    use WithoutMiddleware;
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Branch::factory()->create();
    }

    public function test_get_all_employees()
    {
        $this->get(route('employees.index'))->assertViewIs('employees.index');
    }

    public function test_store_employees()
    {
        $employee = Employee::factory()->make();
        $this->json('POST', route('employees.store'), $employee->toArray());
        $this->assertDatabaseHas('employees', $employee->toArray());
    }
}
